[package]
name = "lycoris-client"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bytes = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "fs", "sync", "time"] }
tap = "1"

# async
tokio-stream = { version = "0.1", features = ["time", "io-util", "net"] }
tokio-util = { version = "0.7", features = ["io"] }
futures-util = { version = "0.3", features = ["io"] }
futures-channel = { version = "0.3", features = ["sink"] }
async-trait = "0.1"

# http proxy
http-body = "0.4"

# log
tracing = "0.1"
tracing-subscriber = "0.3"

# bpf
aya = { git = "https://github.com/aya-rs/aya", rev = "58f1ecb", features = ["async_tokio"] }
aya-log = { git = "https://github.com/aya-rs/aya", rev = "58f1ecb" }
tracing-log = "0.1"

# auth
totp-rs = { version = "5", features = ["otpauth"] }

# http/2
http = "0.2"
hyper = { version = "0.14", features = ["server", "runtime", "http1", "http2", "stream"] }
hyper-rustls = { version = "0.24", features = ["http2", "logging"] }

# tls
tokio-rustls = "0.24"
rustls-pemfile = "1"
webpki-roots = "0.23"
webpki = { version = "0.22", features = ["std"] }

# config and args
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "3", features = ["derive", "color", "suggestions"] }

# ip addr
cidr = "0.2"
trust-dns-resolver = "0.22"

share = { path = "../share" }

[dev-dependencies]
nix = "0.26"
h2 = { version = "0.3", features = ["stream"] }
