[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bytes = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "fs", "sync", "time"] }
tap = "1"

# async
tokio-util = { version = "0.7", features = ["compat"] }
futures-util = { version = "0.3", features = ["io"] }
futures-channel = { version = "0.3", features = ["sink"] }
async-trait = "0.1"

# log
tracing = "0.1"
tracing-subscriber = "0.3"

# bpf log
aya-log = { git = "https://github.com/aya-rs/aya-log", branch = "main" }
simplelog = "0.12"

# auth
totp-rs = "2"

# http/2
h2 = { version = "0.3", features = ["stream"] }
http = "0.2"

# tls
tokio-rustls = "0.23"
rustls-pemfile = "1"
webpki-roots = "0.22"

# config and args
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "3", features = ["derive", "color", "suggestions"] }

# bpf
aya = { version = "0.11", features = ["async_tokio"] }

# ip addr
cidr = "0.2"

share = { path = "../share" }

[dev-dependencies]
nix = "0.24"
