[package]
name = "lycoris-server"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bytes = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "fs"] }
tokio-util = { version = "0.7", features = ["io"] }
futures-util = { version = "0.3", features = ["io"] }
tap = "1"

# log
tracing = "0.1"
tracing-subscriber = "0.3"

# auth
totp-rs = { version = "5", features = ["otpauth"] }

# http/2
http = "0.2"
hyper = { version = "0.14", features = ["runtime", "http2", "http1", "server", "stream"] }

# tls
tokio-rustls = "0.24"
rustls-pemfile = "1"

# config and args
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "3", features = ["derive", "color", "suggestions"] }

share = { path = "../share" }

[dev-dependencies]
webpki = { version = "0.22", features = ["std"] }
hyper-rustls = { version = "0.24", features = ["http2", "logging"] }
hyper = { version = "0.14", features = ["client"] }
