[package]
name = "lycoris-bpf"
version = "0.4.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
unroll = "0.1"

[build-dependencies]
bindgen = "0.72.0"
