[package]
name = "share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aya = { version = "0.11", optional = true }
h2 = { version = "0.3", optional = true, features = ["stream"] }
futures-util = { version = "0.3", optional = true, features = ["io"] }
bytes = { version = "1", optional = true }
tokio = { version = "1", optional = true, features = ["macros", "rt"] }
http = { version = "0.2", optional = true }

[features]
userspace = ["aya", "h2", "futures-util", "bytes", "tokio", "http"]
