[package]
name = "share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = { version = "0.3", features = ["stream"] }
futures-util = { version = "0.3", features = ["io"] }
bytes = "1"
tokio = { version = "1", features = ["macros", "rt", "io-util", "net"] }
tokio-stream = { version = "0.1", features = ["time", "io-util"] }
http = "0.2"
tap = "1"
tracing = "0.1"
